#!/bin/bash
DIR="$PWD/environment"
DK_CMD="docker-compose -f environment/docker/docker-compose.yml --env-file .env.development"
TR_CMD="$DIR/terraform/cli"

# Initiating containers
$DK_CMD up -d

# Initiating Terraform
[ -e "$DIR/terraform/.terraform" ] || $TR_CMD init

# Waiting for the RabbitMQ to become available
while $DK_CMD exec rabbitmq rabbitmqctl status > /dev/null; [[ $? -ne 0 ]]; do
  echo "Trying to connect to RabbitMQ..."
  sleep 5
done

# Applying Terraform script
$TR_CMD apply -auto-approve

# Run migrations
npm run typeorm:dev migration:run
npm run typeorm:test migration:run

echo "\nDevpay dependencies initialization finished 🎉🎉🎉"