#!/bin/bash
DIR="$PWD/environment"
DK_CMD="docker-compose -f environment/docker/docker-compose.yml --env-file .env.development"
TR_CMD="$DIR/terraform/cli"

# Initiating containers
$DK_CMD up -d

# Initiating replica-sets
MONGO_CMD="$DK_CMD exec mongo_database mongo -u admin -p secure --authenticationDatabase admin --eval rs.initiate() --quiet"
while $MONGO_CMD; [[ $? -ne 0 ]]; do
  sleep 2
done

# Initiating Terraform
[ -e "$DIR/terraform/.terraform" ] || $TR_CMD init

# Waiting for the RabbitMQ to become available
while $DK_CMD exec rabbitmq rabbitmqctl status > /dev/null; [[ $? -ne 0 ]]; do
  echo "Trying to connect to RabbitMQ..."
  sleep 5
done

# Applying Terraform script
if $TR_CMD apply -auto-approve; [[ $? -ne 0 ]]; then
  $TR_CMD apply -destroy -auto-approve -refresh=false
  $TR_CMD apply -auto-approve
fi

echo "\nDevpay dependencies initialization finished 🎉🎉🎉"