version: '3'

services:
  mysql_database:
    container_name: devpay_mysql_database
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - devpay_mysql:/var/lib/mysql
    ports:
      - $MYSQL_DATABASE_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DATABASE_PASS
    networks:
      - devpay

  mongo_database:
    container_name: devpay_mongo_database
    image: mongo:focal
    restart: always
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - devpay_mongo:/data/db
    ports:
      - $MONGO_DATABASE_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure
    networks:
      - devpay

  rabbitmq:
    container_name: devpay_rabbitmq
    image: bitnami/rabbitmq:latest
    restart: always
    volumes:
      - devpay_rabbitmq:/bitnami
    ports:
      - $RABBITMQ_MANAGEMENT_PORT:15672
      - $RABBITMQ_PORT:5672
    environment:
      RABBITMQ_USERNAME: $RABBITMQ_USER
      RABBITMQ_PASSWORD: $RABBITMQ_PASS
      RABBITMQ_PLUGINS: 'rabbitmq_management'
    networks:
      - devpay

volumes:
  devpay_mysql:
  devpay_mongo:
  devpay_rabbitmq:

networks:
  devpay:
    name: devpay
