version: '3'

services:
  mysql_database:
    container_name: devpay_mysql_database
    image: mysql:8
    restart: always
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - devpay_mysql:/var/lib/mysql
    ports:
      - $MYSQL_DATABASE_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DATABASE_PASS
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - devpay

  mongo_database:
    container_name: devpay_mongo_database
    image: mongo:focal
    restart: always
    volumes:
      - ./mongo/keyfile.txt:/data/keyfile.txt
      - ./mongo/init:/docker-entrypoint-initdb.d
      - devpay_mongo:/data/db
    ports:
      - $MONGO_DATABASE_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure
    command: --bind_ip_all --replSet rs0 --keyFile /data/keyfile.txt
    networks:
      - devpay

  rabbitmq:
    container_name: devpay_rabbitmq
    image: bitnami/rabbitmq:latest
    restart: always
    volumes:
      - devpay_rabbitmq:/bitnami
    ports:
      - $RABBITMQ_MANAGEMENT_PORT:15672
      - $RABBITMQ_PORT:5672
    environment:
      RABBITMQ_USERNAME: $RABBITMQ_USER
      RABBITMQ_PASSWORD: $RABBITMQ_PASS
      RABBITMQ_PLUGINS: 'rabbitmq_management'
    networks:
      - devpay

  acquirer_app:
    container_name: devpay_acquirer_app
    build: ./apps/acquirer
    image: devpay/fake-acquirer
    restart: always
    volumes:
      - ./apps/acquirer/db.json:/home/node/app/db.json
    ports:
      - $ACQUIRER_SERVICE_PORT:3000
    working_dir: /home/node/app
    command: json-server --host 0.0.0.0 --port 3000 db.json
    networks:
      - devpay

  anti_fraud_app:
    container_name: devpay_anti_fraud_app
    image: node:16.14.0
    restart: always
    volumes:
      - ./apps/anti-fraud:/home/node/app
    ports:
      - $ANTI_FRAUD_SERVICE_PORT:3000
    working_dir: /home/node/app
    command: node ./main.js
    networks:
      - devpay

volumes:
  devpay_mysql:
  devpay_mongo:
  devpay_rabbitmq:

networks:
  devpay:
    name: devpay
